server:
  port: 9009 #提供者的端口
spring:
  application:
    name: spring-cloud-nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.200:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
